### ISSUE TITLE
Data type style visualisation

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-hexeditor#164]
Working with color can be challenging. I studied graphic design, which means nothing, so here a image that hopefully shows that I have a certain level of quality in me:

![](http://doekewartena.nl/work/files/gimgs/11_network104798087.jpg)

There are a lot of data types, and I expect more to come like 128bit types, since some processors can work with those as well those days.

When it comes to the relation of interpreting color to data in the brain (so not in the computer), then we humans are really bad at this. Sure we can see a lot of colors, but it is different when we have to map them to a specific value in our head. I cant remember what it was but it is below 10. Pretty sure it was below 8 as well. I think it was 4, after that the brain has to think to hard. Sure practice will make it more easy over time.

Anyway, I was thinking, between signed and unsigned, maybe a line pattern can be used:

<img width="156" alt="Screen Shot 2020-07-29 at 11 29 33" src="https://user-images.githubusercontent.com/738650/88783421-0b663e80-d18f-11ea-88cb-bf794907d0d6.png">

Anyway, instead of having an array in `settings.json` like:

```json
{
    "type": "Int8",
    "color": "#0F0",
    "backgroundColor": "#202020"
},
```
It might be nice to have a something like:

```json
hexeditor.css_style_file = "path/to/file.css";
```

So we can use css like:

```css
.type--Int8 {
    background-image: linear-gradient(45deg, #98CD8D 25%, #F6F0CF 25%, #F6F0CF 50%, #98CD8D 50%, #98CD8D 75%, #F6F0CF 75%, #F6F0CF 100%);
    background-size: 56.57px 56.57px;
}
.type--Float32 {
   ...
}

```
