### ISSUE TITLE
Decode Text overlap ("editor.fontSize": 20)

### ISSUE THREAD

**Issue by thefatwhale** [microsoft/vscode-hexeditor#286]
[![gmxQk4.png](https://z3.ax1x.com/2021/05/04/gmxQk4.png)](https://imgtu.com/i/gmxQk4)

↑ 'decode text' some line overlap (in orange rectangle).
screenshot in 20 editor font size.
> vscode 1.55.2
windows 7 x64
hex editor 1.6.0

**Comment by thefatwhale** [comment]
？？？

**Comment by thefatwhale** [comment]
@lramos15 
Has this bug been fixed?
In my test add below code can fix
add into `.\dist\hexEdit.css`
```css
#hexbody>.row {
    display: flex;
}

#ascii>.row {
    display: flex;
}
```
but am not sure that's the best solution to fix this.
