### ISSUE TITLE
Support for binary templates using Kaitai Struct

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode-hexeditor#50]
Hex editors are usually used for binary file formats. Currently only the file bytes are displayed (in hex), and to see a UInt32 value you have to know where it is in the file and move the cursor to it.

Most hex editors include a feature that allows to define binary templates for different file formats and view the parsed results as JSON or similar.

The cross-editor standard for binary templates is Kaitai Struct - https://kaitai.io/

It supports integration with many programming languages, it is free and open source, and it has a lot of community-contributed templates for many popular file formats - https://formats.kaitai.io/

The templates are defined using YAML, with a `.ksy` file extension.

Example template:
```
seq:
  - id: length
    type: u32
  - id: contents
    type: str
    size: length
    encoding: UTF-8
  - id: has_crc
    type: u1
  - id: crc32
    type: u4
    if: has_crc32 != 0
```

This will generate a JS class that you can pass the file data to and it will give you the parsed result.

What do you think?
